# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gQ-l9hdFlsp_imE2VamPI_r-YjCuyw2y
"""
pip install streamlit , seaborn
import streamlit as st
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score, mean_absolute_error
import numpy as np

# 1. Load data
@st.cache_data
def load_data():
    df = pd.read_csv("detox_2.csv")
    return df

df = load_data()

st.title("Digital Detox Impact Analyzer (Simple Demo)")

st.write("Dataset preview:")
st.dataframe(df.head())

# 2. EDA section
st.header("Exploratory Data Analysis")

numeric_cols = ["age", "screen_time", "social_media_hrs",
                "detox_duration_hrs", "mood_improv",
                "stress_red", "sleep_improv", "focus_improve"]

st.subheader("Summary statistics")
st.write(df[numeric_cols].describe())

st.subheader("Correlation heatmap")
fig, ax = plt.subplots(figsize=(8, 6))
sns.heatmap(df[numeric_cols].corr(), annot=True, cmap="coolwarm", ax=ax)
st.pyplot(fig)

st.subheader("Screen time vs Mood improvement")
fig2, ax2 = plt.subplots()
sns.scatterplot(data=df, x="screen_time", y="mood_improv", ax=ax2)
st.pyplot(fig2)

# 3. Simple Linear Regression Model
st.header("Linear Regression Model")

st.write("Target: mood_improv; Features: age, screen_time, social_media_hrs, detox_duration_hrs.")

X = df[["age", "screen_time", "social_media_hrs", "detox_duration_hrs"]]
y = df["mood_improv"]

# train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# scale features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = LinearRegression()
model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

st.write(f"R2 score: {r2:.3f}")
st.write(f"Mean Absolute Error: {mae:.3f}")

st.subheader("Predicted vs Actual mood_improv (test set)")
fig3, ax3 = plt.subplots()
ax3.scatter(y_test, y_pred)
ax3.set_xlabel("Actual")
ax3.set_ylabel("Predicted")
ax3.axline((0, 0), slope=1, color="red", linestyle="--")
st.pyplot(fig3)

# 4. Interactive prediction
st.header("Try your own inputs")

age_input = st.slider("Age", 18, 50, 22)
screen_time_input = st.slider("Daily screen time (hours)", 3, 14, 8)
social_media_input = st.slider("Social media hours", 0, 12, 4)
detox_duration_input = st.selectbox("Detox duration (hours)", [24, 48])

if st.button("Predict mood improvement"):
    input_df = pd.DataFrame([{
        "age": age_input,
        "screen_time": screen_time_input,
        "social_media_hrs": social_media_input,
        "detox_duration_hrs": detox_duration_input,
    }])

    input_scaled = scaler.transform(input_df)
    pred_mood = model.predict(input_scaled)[0]

    st.success(f"Predicted mood improvement: {pred_mood:.1f}")
    st.info("Note: Low R2 means this simple model does not explain much variance; "
            "this is a demonstration of linear regression on the dataset.")
